### ISSUE TITLE
Pull fixes from coreboot

### ISSUE THREAD

**Issue by stokito** [stokito/grub-invaders#5]
From the page https://www.coreboot.org/GRUB_invaders

GRUB invaders 1.0.0 has 3 problems which are triggered by newer gcc+binutils. A mail with a patch is available [here](https://mail.coreboot.org/pipermail/coreboot/2009-April/046560.html) and the patch is [here](http://www.coreboot.org/pipermail/coreboot/attachments/20090413/4bd0af62/attachment.ksh).

User comment (compiling in Trisquel 6):

I applied the patch above.

When attempting to compile on Trisquel 6 I got this error:

video.c:(.text+0x277): undefined reference to `__stack_chk_fail'
Modify compile.sh, find the line that says:

CFLAGS="-fno-builtin -nostdinc -O2 -I. -Wall -Werror"
Change it to say:

CFLAGS="-fno-builtin -nostdinc -O2 -I. -Wall -Werror -fno-stack-protector"

**Comment by allbombson** [comment]
This can be closed and it was fixed in my pr.
